version: '3'
services:
  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./app:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
  web:
    image: 'nginx'
    depends_on:
      - app
    links:
      - app
    ports:
      - '8080:80'
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
      - ./log/nginx:/var/log/nginx
  # node:
  #   build:
  #     context: .
  #     dockerfile: ./docker/node/Dockerfile
  #   environment:
  #     - NODE_ENV=development
  #   tty: true
  #   volumes:
  #     - ./app:/app
  #   command: "npm run docker-dev"
volumes:
  mysql-data:
